app:
  name: "go-scaffold"
  mode: "dev"
  port: 8080

log:
  level: "debug"
  filename: "go-scaffold.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 13306
  user: "root"
  password: "xxx"
  dbname: "mysql"
redis:
  host: "127.0.0.1"
  port: 16379
  db: 0